TAA-407: Force removal of VM instance on error.
Separate stages so we can create a k8s node for cleanup, CF VM
instance may have already disconnected and terminated.

This at least ensures we do not have any costly VM instances left
in GCP that have no associated Jenkins node. It also cleans up the
testbench if it still exists and reported offline.

Some additional errors checks and recovery, mtkc install can hang
indefinitely due to unattended-upgr and ensure we have removed
any offline testbenches left hanging.

diff --git a/workloads/android/pipelines/tests/cvd_launcher/Jenkinsfile b/workloads/android/pipelines/tests/cvd_launcher/Jenkinsfile
--- a/workloads/android/pipelines/tests/cvd_launcher/Jenkinsfile
+++ b/workloads/android/pipelines/tests/cvd_launcher/Jenkinsfile
@@ -1,4 +1,4 @@
-//  Copyright (c) 2024 Accenture, All Rights Reserved.
+// Copyright (c) 2024 Accenture, All Rights Reserved.
 //
 // Licensed under the Apache License, Version 2.0 (the "License");
 // you may not use this file except in compliance with the License.
@@ -15,6 +15,30 @@
 // Description:
 // Cuttlefish Virtual Device launcher for use with MTK Connect in order to
 // test Cuttlefish Virtual Device images.
+//
+// On error, cleanup VM instances because the GCE plugin can lose connection
+// with GCP and VM instance, leaving the instance running and that adds to
+// cloud costs.
+
+// Used in cleanup stage should prior stages fail.
+def kubernetesPodTemplate = """
+  apiVersion: v1
+  kind: Pod
+  metadata:
+    annotations:
+      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
+  spec:
+    serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
+    containers:
+    - name: builder
+      image: ${CLOUD_REGION}-docker.pkg.dev/${CLOUD_PROJECT}/${ANDROID_BUILD_DOCKER_ARTIFACT_PATH_NAME}:latest
+      imagePullPolicy: IfNotPresent
+      command:
+      - sleep
+      args:
+      - 4h
+""".stripIndent()
+
 pipeline {
 
   parameters {
@@ -52,73 +76,139 @@ pipeline {
            description: '''<p>total memory available to guest (memory_mb option)</p>''')
   }
 
-  agent { label params.JENKINS_GCE_CLOUD_LABEL }
+  agent none
 
   stages {
-    stage ('Launch Virtual Devices') {
-      when { expression { env.CUTTLEFISH_DOWNLOAD_URL } }
-      steps {
-        sh '''
-          CUTTLEFISH_DOWNLOAD_URL="${CUTTLEFISH_DOWNLOAD_URL}" \
-          CUTTLEFISH_MAX_BOOT_TIME="${CUTTLEFISH_MAX_BOOT_TIME}" \
-          NUM_INSTANCES=${NUM_INSTANCES} \
-          VM_CPUS=${VM_CPUS} \
-          VM_MEMORY_MB=${VM_MEMORY_MB} \
-          ./workloads/android/pipelines/tests/cvd_launcher/cvd_start_stop.sh --start
-        '''
-      }
-    }
+    stage ('Start VM Instance') {
+      agent { label params.JENKINS_GCE_CLOUD_LABEL }
 
-    stage ('MTK Connect to Virtual Devices') {
-      when { expression { env.CUTTLEFISH_DOWNLOAD_URL } }
-      steps {
-        withCredentials([usernamePassword(credentialsId: 'jenkins-mtk-connect-apikey', passwordVariable: 'MTK_CONNECT_PASSWORD', usernameVariable: 'MTK_CONNECT_USERNAME')]) {
-          sh '''
-            sudo \
-            MTK_CONNECT_DOMAIN=${HORIZON_DOMAIN} \
-            MTK_CONNECT_USERNAME=${MTK_CONNECT_USERNAME} \
-            MTK_CONNECT_PASSWORD=${MTK_CONNECT_PASSWORD} \
-            MTK_CONNECTED_DEVICES=${NUM_INSTANCES} \
-            MTK_CONNECT_TEST_ARTIFACT="${CUTTLEFISH_DOWNLOAD_URL}" \
-            MTK_CONNECT_TESTBENCH="${JOB_NAME}-${BUILD_NUMBER}" \
-            MTK_CONNECT_NATIVE_LINUX_INSTALL=true \
-            ./workloads/android/pipelines/tests/cvd_launcher/cvd_mtk_connect.sh --start
-          '''
+      stages {
+        stage ('Launch Virtual Devices') {
+          when { expression { env.CUTTLEFISH_DOWNLOAD_URL } }
+          steps {
+            catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
+              script { env.VM_NODE_NAME = env.NODE_NAME }
+              sh '''
+                CUTTLEFISH_DOWNLOAD_URL="${CUTTLEFISH_DOWNLOAD_URL}" \
+                CUTTLEFISH_MAX_BOOT_TIME="${CUTTLEFISH_MAX_BOOT_TIME}" \
+                NUM_INSTANCES=${NUM_INSTANCES} \
+                VM_CPUS=${VM_CPUS} \
+                VM_MEMORY_MB=${VM_MEMORY_MB} \
+                ./workloads/android/pipelines/tests/cvd_launcher/cvd_start_stop.sh --start
+              '''
+            }
+          }
+        }
+
+        stage ('MTK Connect to Virtual Devices') {
+          when {
+            allOf {
+              expression { env.CUTTLEFISH_DOWNLOAD_URL }
+              expression { currentBuild.currentResult == 'SUCCESS' }
+            }
+          }
+          // MTKC installer may error and hang on dpkg lock, so timeout after 15m.
+          steps {
+            withCredentials([usernamePassword(credentialsId: 'jenkins-mtk-connect-apikey', passwordVariable: 'MTK_CONNECT_PASSWORD', usernameVariable: 'MTK_CONNECT_USERNAME')]) {
+              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
+                sh '''
+                  sudo \
+                  MTK_CONNECT_DOMAIN=${HORIZON_DOMAIN} \
+                  MTK_CONNECT_USERNAME=${MTK_CONNECT_USERNAME} \
+                  MTK_CONNECT_PASSWORD=${MTK_CONNECT_PASSWORD} \
+                  MTK_CONNECTED_DEVICES=${NUM_INSTANCES} \
+                  MTK_CONNECT_TEST_ARTIFACT="${CUTTLEFISH_DOWNLOAD_URL}" \
+                  MTK_CONNECT_TESTBENCH="${JOB_NAME}-${BUILD_NUMBER}" \
+                  MTK_CONNECT_NATIVE_LINUX_INSTALL=true \
+                  timeout 15m ./workloads/android/pipelines/tests/cvd_launcher/cvd_mtk_connect.sh --start
+                '''
+              }
+            }
+          }
+        }
+
+        stage ('Keep Devices Alive'){
+          when {
+            allOf {
+              expression { env.CUTTLEFISH_DOWNLOAD_URL }
+              expression { currentBuild.currentResult == 'SUCCESS' }
+            }
+          }
+          steps {
+            catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
+              sh '''
+                CUTTLEFISH_KEEP_ALIVE_TIME="${CUTTLEFISH_KEEP_ALIVE_TIME}" \
+                ./workloads/android/pipelines/tests/cvd_launcher/cvd_start_stop.sh --keep-alive
+              '''
+            }
+          }
+        }
+      }
+      post {
+        always {
+          withCredentials([usernamePassword(credentialsId: 'jenkins-mtk-connect-apikey', passwordVariable: 'MTK_CONNECT_PASSWORD', usernameVariable: 'MTK_CONNECT_USERNAME')]) {
+            catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
+              sh '''
+                if test -n "$CUTTLEFISH_DOWNLOAD_URL"; then
+                  sudo \
+                  MTK_CONNECT_DOMAIN=${HORIZON_DOMAIN} \
+                  MTK_CONNECT_USERNAME=${MTK_CONNECT_USERNAME} \
+                  MTK_CONNECT_PASSWORD=${MTK_CONNECT_PASSWORD} \
+                  MTK_CONNECTED_DEVICES=${NUM_INSTANCES} \
+                  MTK_CONNECT_TESTBENCH="${JOB_NAME}-${BUILD_NUMBER}" \
+                  ./workloads/android/pipelines/tests/cvd_launcher/cvd_mtk_connect.sh --stop || true
+                  ./workloads/android/pipelines/tests/cvd_launcher/cvd_start_stop.sh --stop || true
+                else
+                  echo "Post stage skipped due to conditional"
+                fi
+              '''
+            }
+          }
+          archiveArtifacts artifacts: 'cvd*.log', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
+          archiveArtifacts artifacts: 'cuttlefish*.tgz', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
         }
       }
     }
 
-    stage ('Keep Devices Alive'){
-      when { expression { env.CUTTLEFISH_DOWNLOAD_URL } }
-      steps {
-        sh '''
-          CUTTLEFISH_KEEP_ALIVE_TIME="${CUTTLEFISH_KEEP_ALIVE_TIME}" \
-          ./workloads/android/pipelines/tests/cvd_launcher/cvd_start_stop.sh --keep-alive
-        '''
-      }
-    }
-  }
+    stage ('Cleanup on error') {
+      agent { kubernetes { yaml kubernetesPodTemplate } }
+      stages {
+        // Remove VM instances on error to avoid instances left running.
+        stage ('Remove VM Instance') {
+          when { expression { currentBuild.currentResult != 'SUCCESS' } }
+          steps {
+            container(name: 'builder') {
+              script { VM_NODE_NAME = env.VM_NODE_NAME }
+              sh '''
+                echo "Removing " ${VM_NODE_NAME} " on error!"
+                yes Y | gcloud compute instances delete ${VM_NODE_NAME} --zone ${CLOUD_ZONE} || true
+              '''
+            }
+          }
+        }
 
-  post {
-    always {
-      withCredentials([usernamePassword(credentialsId: 'jenkins-mtk-connect-apikey', passwordVariable: 'MTK_CONNECT_PASSWORD', usernameVariable: 'MTK_CONNECT_USERNAME')]) {
-        sh '''
-          if test -n "$CUTTLEFISH_DOWNLOAD_URL"; then
-            sudo \
-            MTK_CONNECT_DOMAIN=${HORIZON_DOMAIN} \
-            MTK_CONNECT_USERNAME=${MTK_CONNECT_USERNAME} \
-            MTK_CONNECT_PASSWORD=${MTK_CONNECT_PASSWORD} \
-            MTK_CONNECTED_DEVICES=${NUM_INSTANCES} \
-            MTK_CONNECT_TESTBENCH="${JOB_NAME}-${BUILD_NUMBER}" \
-            ./workloads/android/pipelines/tests/cvd_launcher/cvd_mtk_connect.sh --stop || true
-            ./workloads/android/pipelines/tests/cvd_launcher/cvd_start_stop.sh --stop || true
-          else
-            echo "Post stage skipped due to conditional"
-          fi
-        '''
+        stage ('Delete Offline Testbenches') {
+          when { expression { currentBuild.currentResult != 'SUCCESS' } }
+          steps {
+            container(name: 'builder') {
+              withCredentials([usernamePassword(credentialsId: 'jenkins-mtk-connect-apikey', passwordVariable: 'MTK_CONNECT_PASSWORD', usernameVariable: 'MTK_CONNECT_USERNAME')]) {
+                sh '''
+                  sudo apt upgrade -y && \
+                  sudo apt install -y npm nodejs && \
+                  sudo \
+                  MTK_CONNECT_DOMAIN=${HORIZON_DOMAIN} \
+                  MTK_CONNECT_USERNAME=${MTK_CONNECT_USERNAME} \
+                  MTK_CONNECT_PASSWORD=${MTK_CONNECT_PASSWORD} \
+                  MTK_CONNECT_NATIVE_LINUX_INSTALL=false \
+                  MTK_CONNECT_TESTBENCH="${JOB_NAME}-${BUILD_NUMBER}" \
+                  MTK_CONNECT_DELETE_OFFLINE_TESTBENCHES=true \
+                  ./workloads/android/pipelines/tests/cvd_launcher/cvd_mtk_connect.sh --delete || true
+                '''
+              }
+            }
+          }
+        }
       }
-      archiveArtifacts artifacts: 'cvd*.log', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
-      archiveArtifacts artifacts: 'cuttlefish*.tgz', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
     }
   }
 }
